//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIProject.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Another CSV.
        /// </summary>
        public static string AnotherCSV {
            get {
                return ResourceManager.GetString("AnotherCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarize Another Text.
        /// </summary>
        public static string AnotherText {
            get {
                return ResourceManager.GetString("AnotherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAUD DETECTION.
        /// </summary>
        public static string FraudDetection {
            get {
                return ResourceManager.GetString("FraudDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time transaction monitoring and classification.
        /// </summary>
        public static string FraudDetectionDescription {
            get {
                return ResourceManager.GetString("FraudDetectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraud Detection System.
        /// </summary>
        public static string FraudDetectionSystem {
            get {
                return ResourceManager.GetString("FraudDetectionSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRAUD DETECTION RESULTS.
        /// </summary>
        public static string FraudResultTitle {
            get {
                return ResourceManager.GetString("FraudResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Sentiment.
        /// </summary>
        public static string NegativeResource {
            get {
                return ResourceManager.GetString("NegativeResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Sentiment.
        /// </summary>
        public static string PositiveResource {
            get {
                return ResourceManager.GetString("PositiveResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CSV file to train your model..
        /// </summary>
        public static string SelectACSV {
            get {
                return ResourceManager.GetString("SelectACSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENTIMENT ANALYSIS.
        /// </summary>
        public static string SentimentAnalysis {
            get {
                return ResourceManager.GetString("SentimentAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your file, train your model and predict the result!.
        /// </summary>
        public static string SentimentAnalysisDescription {
            get {
                return ResourceManager.GetString("SentimentAnalysisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentiment Analysis System.
        /// </summary>
        public static string SentimentAnalysisSystem {
            get {
                return ResourceManager.GetString("SentimentAnalysisSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CSV File should have Text,Label as labels..
        /// </summary>
        public static string SentimentFileProperties {
            get {
                return ResourceManager.GetString("SentimentFileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENTIMENT ANALYSIS RESULTS.
        /// </summary>
        public static string SentimentResultTitle {
            get {
                return ResourceManager.GetString("SentimentResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a sentence to predict its sentiment..
        /// </summary>
        public static string SentimentText {
            get {
                return ResourceManager.GetString("SentimentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARIZATION RESULTS.
        /// </summary>
        public static string SummarizerResultTitle {
            get {
                return ResourceManager.GetString("SummarizerResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Of Text.
        /// </summary>
        public static string SummaryTitle {
            get {
                return ResourceManager.GetString("SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT SUMMARIZER.
        /// </summary>
        public static string TextSummarizer {
            get {
                return ResourceManager.GetString("TextSummarizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summarizes long documents or articles into shorter summaries using NLP models..
        /// </summary>
        public static string TextSummarizerDescription {
            get {
                return ResourceManager.GetString("TextSummarizerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI-Powered Text Summarizer.
        /// </summary>
        public static string TextSummarizerSystem {
            get {
                return ResourceManager.GetString("TextSummarizerSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your CSV File should have TransactionId, Amount, HourOfDay, MerchantCategory, Location, TransactionType, HistoricalAvgAmount, NumTransactionsLast24h, IsFraud as labels..
        /// </summary>
        public static string TransactionFileProperties {
            get {
                return ResourceManager.GetString("TransactionFileProperties", resourceCulture);
            }
        }
    }
}
